name: Parser tests

on: [push, pull_request]

jobs:
  test_parser:
    strategy:
      fail-fast: false
    name: Testing
    runs-on: ubuntu-latest
    env:
      CC: clang
    steps:
      - name: Prepare tree-sitter
        uses: actions/checkout@v2
        with:
          repository: tree-sitter/tree-sitter

      - name: Prepare tree-sitter-norg
        uses: actions/checkout@v2
        with:
          path: test/fixtures/grammars/norg

      - name: Install tree-sitter CLI
        run: |
          cd test/fixtures/grammars/norg
          npm install tree-sitter-cli
      - name: Run tests
        run: |
          cd test/fixtures/grammars/norg
          ./node_modules/tree-sitter-cli/tree-sitter test
